"""create media, campaign_categories, campaigns, campaign_evidence, campaign_updates tables

Revision ID: 391634d784c3
Revises: 5c562832d5a0
Create Date: 2026-09-12 01:01:01.686391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391634d784c3'
down_revision: Union[str, None] = '5c562832d5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_categories',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['campaign_categories.id'], name='fk_campaign_categories_parent'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_media_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('help_request_id', sa.UUID(), nullable=False),
    sa.Column('agent_profile_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('raised_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_relationship', sa.String(length=128), nullable=True),
    sa.Column('payout_destination_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_profile_id'], ['agent_profiles.id'], name='fk_campaigns_agent_profiles'),
    sa.ForeignKeyConstraint(['category_id'], ['campaign_categories.id'], name='fk_campaigns_categories'),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_requests.id'], name='fk_campaigns_help_requests'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_evidence',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name='fk_campaign_evidence_campaigns'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name='fk_campaign_evidence_media'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name='fk_campaign_evidence_users'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name='fk_campaign_evidence_verified_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_updates',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk_campaign_updates_users'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name='fk_campaign_updates_campaigns'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_updates')
    op.drop_table('campaign_evidence')
    op.drop_table('campaigns')
    op.drop_table('media')
    op.drop_table('campaign_categories')
    # ### end Alembic commands ###
