"""create help_requests, help_request_agents, help_request_events tables

Revision ID: 5c562832d5a0
Revises: 921dbc67dad0
Create Date: 2026-09-12 00:55:21.180182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c562832d5a0'
down_revision: Union[str, None] = '921dbc67dad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_help_requests_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('help_request_agents',
    sa.Column('help_request_id', sa.UUID(), nullable=False),
    sa.Column('agent_profile_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_profile_id'], ['agent_profiles.id'], name='fk_help_request_agents_agent_profiles'),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_requests.id'], name='fk_help_request_agents_help_requests'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('help_request_events',
    sa.Column('help_request_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name='fk_help_request_events_users'),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_requests.id'], name='fk_help_request_events_help_requests'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('help_request_events')
    op.drop_table('help_request_agents')
    op.drop_table('help_requests')
    # ### end Alembic commands ###
